"use client";

import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TabsContext from "@/contexts/tabsContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [currTab, setTab] = useState<"tasks" | "rewards">("tasks");

  return (
    <html lang="en">
      <TabsContext.Provider value={{ currTab: currTab, setTab: setTab }}>
        <body className={inter.className + "flex flex-row"}>
          <Navbar />
          {children}
        </body>
      </TabsContext.Provider>
    </html>
  );
}
